"""Emit src/combining.ts: the code point ranges where Python's unicodedata.combining(ch) != 0.

The Python package strips those characters in normalize(); JavaScript has no equivalent API
(\p{M} is wider and would drop Thai and Indic vowel signs), so the table is generated from the
same source and embedded. Run: python scripts/gen-combining.py
"""

import unicodedata
from pathlib import Path

ranges: list[tuple[int, int]] = []
start: int | None = None
for cp in range(0x110000):
    c = unicodedata.combining(chr(cp)) != 0
    if c and start is None:
        start = cp
    if not c and start is not None:
        ranges.append((start, cp - 1))
        start = None
if start is not None:
    ranges.append((start, 0x10FFFF))

lines = [
    f"// Generated by scripts/gen-combining.py from Python's unicodedata {unicodedata.unidata_version}:",
    "// code point ranges where unicodedata.combining(ch) != 0, so normalize() drops exactly what the",
    "// Python package drops. Do not edit by hand.",
    "export const COMBINING_RANGES: ReadonlyArray<readonly [number, number]> = [",
    *(f"  [0x{a:04X}, 0x{b:04X}]," for a, b in ranges),
    "];",
    "",
]
out = Path(__file__).resolve().parent.parent / "src" / "combining.ts"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"{len(ranges)} ranges -> {out}")
